---
kind: pipeline
name: default

clone:
  disable: true

workspace:
  base: /workspace
  path: src/github.com/presslabs/controller-util

steps:
- name: git
  pull: default
  image: plugins/git
  settings:
    depth: 0
    tags: true

- name: dependencies
  image: presslabs/build:stable
  pull: always
  commands:
  - make build.tools

- name: lint
  image: presslabs/build:stable
  commands:
  - make lint

- name: test
  image: presslabs/build:stable
  commands:
  - make test

trigger:
  event:
  - push
---
kind: signature
hmac: d4fc77a1a18431085f295b8d00ab8a41e3ea28d835f581bcb240205c42bd98c5

...
